name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to Hostinger
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure you have added SSH private key in secrets
        port: 65002  # If your SSH server uses a different port, add this line (e.g., 65002)
        source: "public_html"  # Adjust this to the directory or files you want to copy from your repo
        target: "/var/www/rajondey.com/public_html/wp-content/themes/rdc"  # Adjust this to the destination directory on Hostinger

    - name: Execute post-deployment commands on Hostinger
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 65002
         script: |
          cd /var/www/rajondey.com/public_html/wp-content/themes/rdc 
          git pull origin main 
          chown -R openvc:www-data /var/www/domain.com/public_html 
          chmod -R770 /var/www/domain.com/public_html`
